### ISSUE TITLE
ctab23D is missing

### ISSUE THREAD

**Issue by alexgcsa** [chembl/chembl_webresource_client#107]
Hello, 

When I try to run the example, I get the error:

`AttributeError: 'Client' object has no attribute 'ctab23D'`

Is there a way to calculate the 3D molecule structure ?

Thanks,

Alex

**Comment by eloyfelix** [comment]
Hello Alex, the functionality was deprecated since our logs showed no use of it for a long time. Sorry for the inconvenience. 

RDKit could be used to generate 3D conformers of molecules. This blogpost show some example code of how to do it: https://iwatobipen.wordpress.com/2021/01/31/generate-conformers-script-with-rdkit-rdkit-chemoinformatics/
