### ISSUE TITLE
Fail to import new_client due to API problem

### ISSUE THREAD

**Issue by lpravda** [chembl/chembl_webresource_client#125]
Hi guys, it looks like there is an intermittent API problem. When I try to:  `from chembl_webresource_client.new_client import new_client`
 
it fails with
```
Error getting schema from url https://www.ebi.ac.uk/chembl/api/data/spore with status 500 and msg <!doctype html>
<html lang="en" class="vf-no-js">
  <head>
    <script>
// Detect if JS is on and swap vf-no-js for vf-js on the html element
(function(H){H.className=H.className.replace(/\bvf-no-js\b/,'vf-js')})(document.documentElement);
</script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" media="all" href="/css/styles.css?" /> -->
    <title>Error: 500 | EMBLâs European Bionformatics Institute</title>
```

Can you have a look at the respective API problem? Thank you

**Comment by xixichennn** [comment]
I suspect the problem I've been having since last night is the same as the cause of your problem: some sort of instability of this API.

Although I can import this API, I got the `HttpApplicationError` when I used `pd.DataFrame.from_records()` to download the data I filtered. At first I had doubts this error was related to the large size of data I want to download, but on second thought this is impossible because I managed to run this code during the day yesterday. Then I tried to reduce the size of the data to be retrieved, I find even with the same size data, one second I can run it successfully, and the next I got the `HttpApplicationError` again.

I am concerned that some sort of instability of ChEMBL API has started yesterday (in my case). I hope the developer of this API will fix this issue and tell us user when it is fixed.

Below is my code and the error message.
![image](https://user-images.githubusercontent.com/92102760/219347607-aafd5a0c-a88b-4bae-8008-8a377af85468.png)
![image](https://user-images.githubusercontent.com/92102760/219347843-ff283ae6-fcd2-4ae2-bc11-e13c0c9357d8.png)

**Comment by eloyfelix** [comment]
we are indeed having some instabilities related to the infrastructure in our backend. We are working on it.
@juanfmx2 could you please give an update when it gets stable again? thanks.

**Comment by ismorphism** [comment]
> I suspect the problem I've been having since last night is the same as the cause of your problem: some sort of instability of this API.
> 
> Although I can import this API, I got the `HttpApplicationError` when I used `pd.DataFrame.from_records()` to download the data I filtered. At first I had doubts this error was related to the large size of data I want to download, but on second thought this is impossible because I managed to run this code during the day yesterday. Then I tried to reduce the size of the data to be retrieved, I find even with the same size data, one second I can run it successfully, and the next I got the `HttpApplicationError` again.
> 
> I am concerned that some sort of instability of ChEMBL API has started yesterday (in my case). I hope the developer of this API will fix this issue and tell us user when it is fixed.
> 
> Below is my code and the error message. ![image](https://user-images.githubusercontent.com/92102760/219347607-aafd5a0c-a88b-4bae-8008-8a377af85468.png) ![image](https://user-images.githubusercontent.com/92102760/219347843-ff283ae6-fcd2-4ae2-bc11-e13c0c9357d8.png)

The same problem for me unfortunately. During last two hours 😞

**Comment by juanfmx2** [comment]
@xixichennn @ismorphism @eloyfelix yes, unfortunately this week we have been experiencing some stability issues with our cluster. However, it should be resolved now. Please let me know if you run into any other issues. :)

**Comment by xixichennn** [comment]
> @xixichennn @ismorphism @eloyfelix yes, unfortunately this week we have been experiencing some stability issues with our cluster. However, it should be resolved now. Please let me know if you run into any other issues. :)

Although it worked when you announced it here, I still got the `HttpApplicationError` from time to time:(
