### ISSUE TITLE
Not compatible with Python37 - async is now a keyword

### ISSUE THREAD

**Issue by cthoyt** [chembl/chembl_webresource_client#40]
There are several places where the name `async` has been used as a variable name. Since this is now a keyword in Python37, the interpreter will send a SyntaxError.

@jmarinllao will send a PR soon :)

**Comment by cthoyt** [comment]
Any updates? There are now two distinct pull requests related to this issue

**Comment by dprada** [comment]
To @cthoyt, @jmarinllao and @dmyersturnbull:
I have [a forked repo](https://github.com/dprada/chembl_webresource_client) where 'async' was replaced by 'asynchr' since async is a reserved keyword in Python 3.7. 
I also had to [fork gevent-openssl](https://github.com/dprada/chembl_webresource_client) to build it in conda for Python 3.7.

The package can be checked and tested in the uibcdf channel at conda:
```bash
conda install -c uibcdf gevent-openssl
conda install -c uibcdf chembl_webresource_client
```
I don't think doing a PR solves the Python 3.7 compatibility. Maybe ChEMBL should have its own forked gevent-openssl repo built for Python 3.7.

**Comment by eloyfelix** [comment]
We just pushed some changes to the master branch that should fix most of the issues.
Py2 compatibility is dropped as it's support is expiring by the end of the year. (https://pythonclock.org/, https://python3statement.org/).

We also dropped TargetResource and CompoundResource components that worked using already deprecated endpoints.

You can try it by installing from the master branch. We'll be providing new packages soon.

```
pip install https://github.com/chembl/chembl_webresource_client/archive/master.zip
```

**Comment by eloyfelix** [comment]
New version is already available in pypi: https://pypi.org/project/chembl-webresource-client/

so it can be installed from it:
```
pip install chembl-webresource-client
```

**Comment by cthoyt** [comment]
Wonderful! Thank you!!!
